name: Docker Image CI

on:
  release:
    types: [published, edited]

jobs:

  build_and_publish:
    name: Build and publish
    runs-on: ubuntu-latest

    steps:
    - name: Get release tag
      id: tag_name
      run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
    - uses: actions/checkout@v2
    - name: Build the Docker image
      id: docker_build
      env:
        SOURCE_TAG: ${{steps.tag_name.outputs.SOURCE_TAG}}
      run: docker build . --file Dockerfile --tag timinh/php-apache-mongo:latest && docker build . --file Dockerfile --tag timinh/php-apache-mongo:${{ steps.tag_name.outputs.SOURCE_TAG }}
    - name: Push the Docker image
      id: docker_publish
      env:
        SOURCE_TAG: ${{steps.tag_name.outputs.SOURCE_TAG}}
      run: docker login -u timinh -p ${{ secrets.DOCKER_TOKEN }} && docker push timinh/php-apache-mongo:latest && docker push timinh/php-apache-mongo:${{ steps.tag_name.outputs.SOURCE_TAG }}